name: "Execute AWS SSM Command"
description: "Send a command to an EC2 instance using AWS SSM and wait for its completion."
author: "Your Name <your.email@example.com>"
inputs:
  aws-region:
    description: "The AWS region where the EC2 instance is located."
    required: true
  aws-access-key-id:
    description: "AWS Access Key ID."
    required: true
  aws-secret-access-key:
    description: "AWS Secret Access Key."
    required: true
  instance-tag-name:
    description: "The tag name of the EC2 instance."
    required: false
  instance-id:
    description: "The EC2 instance ID."
    required: false
  command:
    description: "The command to execute on the EC2 instance."
    required: true

runs:
  using: "composite"
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}

    - name: Determine EC2 Instance ID
      id: determine_instance_id
      shell: bash
      run: |
        if [ -n "${{ inputs.instance-id }}" ]; then
          echo "Using provided instance ID: ${{ inputs.instance-id }}"
          echo "INSTANCE_ID=${{ inputs.instance-id }}" >> $GITHUB_ENV
        elif [ -n "${{ inputs.instance-tag-name }}" ]; then
          echo "Resolving instance ID from tag name: ${{ inputs.instance-tag-name }}"
          INSTANCE_ID=$(aws ec2 describe-instances --filters "Name=instance-state-name,Values=running" \
          "Name=tag:Name,Values='${{ inputs.instance-tag-name }}'" \
          --query "Reservations[*].Instances[*].InstanceId" --output text)
          if [ -z "$INSTANCE_ID" ]; then
            echo "No running instance found with tag name '${{ inputs.instance-tag-name }}'"
            exit 1
          fi
          echo "Resolved Instance ID: $INSTANCE_ID"
          echo "INSTANCE_ID=$INSTANCE_ID" >> $GITHUB_ENV
        else
          echo "Either instance-id or instance-tag-name must be provided."
          exit 1
        fi

    - name: Execute command on EC2 via SSM
      id: execute_command
      shell: bash
      run: |
        ESCAPED_COMMAND=$(echo "${{ inputs.command }}" | sed 's/\"/\\\"/g')
        COMMAND_ID=$(aws ssm send-command \
          --instance-id $INSTANCE_ID \
          --document-name "AWS-RunShellScript" \
          --comment "Execute script on EC2" \
          --parameters commands="$ESCAPED_COMMAND" \
          --query "Command.CommandId" \
          --output text)
        echo "COMMAND_ID=$COMMAND_ID" >> $GITHUB_ENV

    - name: Wait for command completion and set outputs
      id: wait_and_set_outputs
      shell: bash
      run: |
        while true; do
          STATUS=$(aws ssm get-command-invocation \
              --command-id $COMMAND_ID \
              --instance-id $INSTANCE_ID \
              --query 'Status' \
              --output text)

          if [ "$STATUS" == "Success" ]; then
            OUTPUT=$(aws ssm get-command-invocation \
                --command-id $COMMAND_ID \
                --instance-id $INSTANCE_ID \
                --query 'StandardOutputContent' \
                --output text)
            
            ERROR=$(aws ssm get-command-invocation \
                --command-id $COMMAND_ID \
                --instance-id $INSTANCE_ID \
                --query 'StandardErrorContent' \
                --output text)
            
            echo "Command Output: $OUTPUT"
            echo "Command Errors (if exist): $ERROR"
            echo "::set-output name=command-output::$OUTPUT"
            echo "::set-output name=command-error::$ERROR"
            break
          elif [ "$STATUS" == "Failed" ] || [ "$STATUS" == "Cancelled" ]; then
            echo "Command failed or was cancelled."
            OUTPUT=$(aws ssm get-command-invocation \
                --command-id $COMMAND_ID \
                --instance-id $INSTANCE_ID \
                --query 'StandardOutputContent' \
                --output text)
            
            ERROR=$(aws ssm get-command-invocation \
                --command-id $COMMAND_ID \
                --instance-id $INSTANCE_ID \
                --query 'StandardErrorContent' \
                --output text)
            
            echo "Command Output: $OUTPUT"
            echo "Command Errors (if exist): $ERROR"
            echo "::set-output name=command-output::$OUTPUT"
            echo "::set-output name=command-error::$ERROR"
            exit 1
          else
            echo "Waiting for command to finish..."
            sleep 2
          fi
        done
